/**
 * KodBook API
 *
 * Contact: support@kodbook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthUserDto } from './authUserDto';


export interface ApiResponseAuthUserDto { 
    success?: boolean;
    message?: string;
    data?: AuthUserDto;
    timestamp?: string;
}

