/**
 * KodBook API
 *
 * Contact: support@kodbook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileRegisterDto } from './userProfileRegisterDto';


export interface ApiResponseUserProfileRegisterDto { 
    success?: boolean;
    message?: string;
    data?: UserProfileRegisterDto;
    timestamp?: string;
}

