/**
 * KodBook API
 *
 * Contact: support@kodbook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Authentication Response
 */
export interface AuthResponse { 
    /**
     * Access Token
     */
    accessToken?: string;
    /**
     * Refresh Token
     */
    refreshToken?: string;
    /**
     * Token Type
     */
    tokenType?: string;
    /**
     * Token Expiration Time
     */
    expiresIn?: number;
    /**
     * Message
     */
    message?: string;
}

