/**
 * KodBook API
 *
 * Contact: support@kodbook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body for user authentication.
 */
export interface AuthRequest { 
    /**
     * Username of the user.
     */
    username: string;
    /**
     * Password of the user.
     */
    password: string;
}

