/**
 * KodBook API
 *
 * Contact: support@kodbook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthUserDto { 
    publicId?: string;
    username?: string;
    email?: string;
    role?: AuthUserDto.RoleEnum;
    createdAt?: string;
    updatedAt?: string;
}
export namespace AuthUserDto {
    export const RoleEnum = {
        User: 'USER',
        Admin: 'ADMIN',
        Actuator: 'ACTUATOR',
        Service: 'SERVICE'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


