/**
 * KodBook API
 *
 * Contact: support@kodbook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to change password.
 */
export interface ChangePasswordRequest { 
    /**
     * Current password of the user
     */
    oldPassword: string;
    /**
     * New password to be set
     */
    newPassword: string;
    /**
     * OTP for password change
     */
    otp: string;
}

