/**
 * KodBook API
 *
 * Contact: support@kodbook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model of error response
 */
export interface ErrorResponse { 
    timestamp?: string;
    status?: number;
    error?: string;
    message?: string;
    path?: string;
}

