/**
 * KodBook API
 *
 * Contact: support@kodbook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';


export interface PagedModel { 
    content?: Array<object>;
    page?: PageMetadata;
}

