/**
 * KodBook API
 *
 * Contact: support@kodbook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: number;
    username?: string;
    email?: string;
    dateOfBirth?: string;
    gender?: string;
    city?: string;
    bio?: string;
    college?: string;
    linkedIn?: string;
    gitHub?: string;
}

